DELIMITER $$
DROP EVENT IF EXISTS run_proc_call $$
CREATE
EVENT `run_proc_call` 
ON SCHEDULE EVERY 1 DAY STARTS '2020-09-13 23:55:55'
ON COMPLETION NOT PRESERVE ENABLE
DO 
BEGIN
  call backup_main_tables();
END $$
DELIMITER ;
